// Auto-generated by TorchFX-to-NNTrainer converter
// Model: lfm2 (decoder_only)
// Inherits from causallm::CausalLM

#include "lfm2_700m.h"
#include <model.h>
#include <tensor_api.h>
#include <app_context.h>
#include <engine.h>

#include <embedding_layer.h>
#include <mha_core.h>
#include <transpose_layer.h>
#include <rms_norm.h>
#include <reshaped_rms_norm.h>
#include <swiglu.h>
#include <tie_word_embedding.h>
#include <custom_multiply.h>
#include <custom_slice.h>
#include <causal_conv1d_layer.h>

using ml::train::createLayer;
using ml::train::Tensor;
using LayerHandle = ml::train::LayerHandle;

template <typename T>
static std::string withKey(const std::string &key, T val) {
  return key + "=" + std::to_string(val);
}

template <>
std::string withKey(const std::string &key, std::string val) {
  return key + "=" + val;
}

template <>
std::string withKey(const std::string &key, const char *val) {
  return key + "=" + std::string(val);
}

namespace causallm {

Lfm2CausalLM::Lfm2CausalLM(json &cfg, json &generation_cfg, json &nntr_cfg)
  : Transformer(cfg, generation_cfg, nntr_cfg, ModelType::CAUSALLM),
    CausalLM(cfg, generation_cfg, nntr_cfg),
    Lfm2Transformer(cfg, generation_cfg, nntr_cfg) {
  setupParameters(cfg, generation_cfg, nntr_cfg);
}

Tensor
Lfm2Transformer::createAttention(const int layer_id, int seq_len, int n_heads,
                         int head_dim, Tensor query,
                         Tensor key, Tensor value) {

  using ml::train::createLayer;

  auto V_name = "layer" + std::to_string(layer_id) + "_wv";
  auto K_name = "layer" + std::to_string(layer_id) + "_wk";
  auto Q_name = "layer" + std::to_string(layer_id) + "_wq";
  auto K_norm_name = "layer" + std::to_string(layer_id) + "_k_norm";
  auto Q_norm_name = "layer" + std::to_string(layer_id) + "_q_norm";
  auto A_name = "layer" + std::to_string(layer_id) + "_attention";
  auto O_name = "layer" + std::to_string(layer_id) + "_attention_out";

  // V projection
  LayerHandle v_proj(createLayer("fully_connected", {
    withKey("name", V_name),
    withKey("unit", head_dim * n_heads / GQA_SIZE),
    withKey("disable_bias", "true")
  }));
  Tensor v_proj_out = v_proj(value);

  // K projection
  LayerHandle k_proj(createLayer("fully_connected", {
    withKey("name", K_name),
    withKey("unit", head_dim * n_heads / GQA_SIZE),
    withKey("disable_bias", "true")
  }));
  Tensor k_proj_out = k_proj(key);

  // Q projection
  LayerHandle q_proj(createLayer("fully_connected", {
    withKey("name", Q_name),
    withKey("unit", head_dim * n_heads),
    withKey("disable_bias", "true")
  }));
  Tensor q_proj_out = q_proj(query);

  // K norm (reshaped RMS norm)
  LayerHandle k_norm(createLayer("reshaped_rms_norm", {
    withKey("name", K_norm_name),
    withKey("packed", "false"),
    withKey("epsilon", NORM_EPS),
    withKey("feature_size", head_dim)
  }));
  Tensor k_norm_out = k_norm(k_proj_out);

  // Q norm (reshaped RMS norm)
  LayerHandle q_norm(createLayer("reshaped_rms_norm", {
    withKey("name", Q_norm_name),
    withKey("packed", "false"),
    withKey("epsilon", NORM_EPS),
    withKey("feature_size", head_dim)
  }));
  Tensor q_norm_out = q_norm(q_proj_out);

  // Attention core layer
  LayerHandle attn(createLayer("mha_core", {
    withKey("name", A_name),
    withKey("num_heads", n_heads),
    withKey("num_heads_kv", n_heads / GQA_SIZE),
    withKey("max_timestep", std::to_string(INIT_SEQ_LEN + NUM_TO_GENERATE)),
    withKey("sliding_window", SLIDING_WINDOW),
    withKey("rope_theta", ROPE_THETA),
    withKey("max_position_embeddings", MAX_POSITION_EMBEDDINGS),
    withKey("max_new_tokens", NUM_TO_GENERATE)
  }));
  Tensor attn_out = attn({q_norm_out, k_norm_out, v_proj_out});

  // O projection
  LayerHandle o_proj(createLayer("fully_connected", {
    withKey("name", O_name),
    withKey("unit", DIM),
    withKey("disable_bias", "true")
  }));
  Tensor o_proj_out = o_proj(attn_out);

  return o_proj_out;
}

void Lfm2Transformer::registerCustomLayers() {
  auto &ct_engine = nntrainer::Engine::Global();
  auto app_context =
    static_cast<nntrainer::AppContext *>(ct_engine.getRegisteredContext("cpu"));
  try {
    app_context->registerFactory(nntrainer::createLayer<causallm::ReshapedRMSNormLayer>);
    app_context->registerFactory(nntrainer::createLayer<causallm::TransposeLayer>);
    app_context->registerFactory(nntrainer::createLayer<causallm::CustomMultiplyLayer>);
    app_context->registerFactory(nntrainer::createLayer<causallm::CustomSliceLayer>);
  } catch (std::invalid_argument &e) {
    std::cerr << "failed to register factory, reason: " << e.what() << std::endl;
  }
}

void Lfm2CausalLM::constructModel() {

  using ml::train::createLayer;
  
  // Create input tensor
  LayerHandle input_layer = createLayer("input", {
    withKey("name", "input0"),
    withKey("input_shape", "1:1:" + std::to_string(INIT_SEQ_LEN))
  });
  Tensor input = input_layer(Tensor());
  std::vector<Tensor> all_inputs = {input};

  // Embedding layer
  const std::string embedding_type = TIE_WORD_EMBEDDINGS ? "tie_word_embeddings" : "embedding_layer";
  LayerHandle embedding(createLayer(embedding_type, {
    withKey("name", "embedding0"),
    withKey("in_dim", NUM_VOCAB),
    withKey("out_dim", DIM)
  }));
  Tensor x = embedding(input);

  // Per-layer operator types
  std::vector<std::string> LAYER_TYPES = {
    "conv",
    "conv",
    "attention",
    "conv",
    "conv",
    "attention",
    "conv",
    "conv",
    "attention",
    "conv",
    "attention",
    "conv",
    "attention",
    "conv",
    "attention",
    "conv"
  };

  // Hybrid transformer blocks
  for (int i = 0; i < NUM_LAYERS; ++i) {
    if (LAYER_TYPES[i] == "attention") {
      x = createTransformerDecoderBlock(i, x);
    } else if (LAYER_TYPES[i] == "conv") {
      x = createConvBlock(i, x);
    }
  }

  // Final normalization
  LayerHandle output_norm(createLayer("rms_norm", {
    withKey("name", "output_norm"),
    withKey("epsilon", std::to_string(NORM_EPS)),
    withKey("packed", "false")
  }));
  Tensor norm_out = output_norm(x);

  // LM head
  const std::string lmhead_type = TIE_WORD_EMBEDDINGS ? "tie_word_embeddings" : "lm_head";

  std::cerr << "lmhead_type=" << lmhead_type
            << ", TIE_WORD_EMBEDDINGS=" << TIE_WORD_EMBEDDINGS
            << std::endl;

  std::vector<std::string> lmhead_props = {
    withKey("name", "output_of_causallm"),
    withKey("unit", NUM_VOCAB),
    withKey("disable_bias", "true")
    , withKey("shared_from", "embedding0")
  };
  LayerHandle lmhead(createLayer(lmhead_type, lmhead_props));
  Tensor output = lmhead(norm_out);

  // Compile model from symbolic tensor graph
  model->compile(input, output, ml::train::ExecutionMode::INFERENCE);
}

Tensor
Lfm2CausalLM::createConvBlock(const int layer_id,
  Tensor input) {

  using ml::train::createLayer;
  auto prefix = "layer" + std::to_string(layer_id);

  // Pre-conv normalization
  LayerHandle conv_norm(createLayer("rms_norm", {
    withKey("name", prefix + "_conv_norm"),
    withKey("epsilon", std::to_string(NORM_EPS)),
    withKey("packed", "false")
  }));
  Tensor normed = conv_norm(input);

  // Conv operator (tensor-level operations)
  LayerHandle conv_op_0(createLayer("fully_connected", {
    withKey("name", prefix + "_conv_in_proj"),
    withKey("unit", 4608),
    withKey("disable_bias", "true")
  }));
  Tensor conv_op_0_out = conv_op_0(normed);

  LayerHandle conv_op_1(createLayer("custom_transpose", {
    withKey("name", prefix + "_conv_transpose"),
    withKey("perm", "2:0:1")
  }));
  Tensor conv_op_1_out = conv_op_1(conv_op_0_out);

  LayerHandle conv_op_2(createLayer("split", {
    withKey("name", prefix + "_conv_model_layers_0_conv_chunk"),
    withKey("axis", 1),
    withKey("split_number", 3)
  }));
  Tensor conv_op_2_out = conv_op_2(conv_op_1_out);

  // Indexed outputs from split/chunk
  Tensor chunk_0 = conv_op_2_out.output(0);
  Tensor chunk_1 = conv_op_2_out.output(1);
  Tensor chunk_2 = conv_op_2_out.output(2);

  LayerHandle conv_op_3(createLayer("custom_multiply", {
    withKey("name", prefix + "_conv_model_layers_0_conv_mul")
  }));
  Tensor conv_op_3_out = conv_op_3({chunk_0, chunk_2});

  LayerHandle conv_op_4(createLayer("depthwiseconv1d", {
    withKey("name", prefix + "_conv_conv"),
    withKey("filters", 1536),
    withKey("kernel_size", 3),
    withKey("stride", 1),
    withKey("padding", 2),
    withKey("dilation", 1),
    withKey("disable_bias", "true")
  }));
  Tensor conv_op_4_out = conv_op_4(conv_op_3_out);

  LayerHandle conv_op_5(createLayer("custom_slice", {
    withKey("name", prefix + "_conv_model_layers_0_conv___getitem___1"),
    withKey("axis", 3),
    withKey("start_index", 1),
    withKey("end_index", INIT_SEQ_LEN + 1)
  }));
  Tensor conv_op_5_out = conv_op_5(conv_op_4_out);

  LayerHandle conv_op_6(createLayer("custom_multiply", {
    withKey("name", prefix + "_conv_model_layers_0_conv_mul_1")
  }));
  Tensor conv_op_6_out = conv_op_6({chunk_1, conv_op_5_out});

  LayerHandle conv_op_7(createLayer("custom_transpose", {
    withKey("name", prefix + "_conv_transpose_1"),
    withKey("perm", "1:2:0")
  }));
  Tensor conv_op_7_out = conv_op_7(conv_op_6_out);

  LayerHandle conv_op_8(createLayer("fully_connected", {
    withKey("name", prefix + "_conv_out_proj"),
    withKey("unit", 1536),
    withKey("disable_bias", "true")
  }));
  Tensor conv_op_8_out = conv_op_8(conv_op_7_out);

  // Conv residual connection
  Tensor residual = input.add(conv_op_8_out);

  // Pre-FFN normalization
  LayerHandle ffn_norm(createLayer("rms_norm", {
    withKey("name", prefix + "_ffn_norm"),
    withKey("epsilon", std::to_string(NORM_EPS)),
    withKey("packed", "false")
  }));
  Tensor ffn_normed = ffn_norm(residual);

  // Feed forward
  Tensor ffn_out = createMlp(layer_id, DIM, INTERMEDIATE_SIZE, ffn_normed);

  // FFN residual connection
  Tensor block_out = residual.add(ffn_out);

  return block_out;
}

void Lfm2CausalLM::setupParameters(json &cfg, json &generation_cfg,
                                        json &nntr_cfg) {
  CausalLM::setupParameters(cfg, generation_cfg, nntr_cfg);

  try {
    unsigned int ff_dim = cfg["block_ff_dim"].get<unsigned int>();  // 10240

    if (cfg.contains("block_auto_adjust_ff_dim") &&
        cfg["block_auto_adjust_ff_dim"].get<bool>()) {
      ff_dim = static_cast<unsigned int>((2.0f * ff_dim) / 3.0f);   // 6826
    }

    float mult = cfg.contains("block_ffn_dim_multiplier")
                  ? cfg["block_ffn_dim_multiplier"].get<float>()
                  : 1.0f;
    ff_dim = static_cast<unsigned int>(ff_dim * mult);

    unsigned int multiple_of = cfg.contains("block_multiple_of")
                                ? cfg["block_multiple_of"].get<unsigned int>()
                                : 1;
    ff_dim = multiple_of * ((ff_dim + multiple_of - 1) / multiple_of);  // 6912

    INTERMEDIATE_SIZE = ff_dim;

    // LFM2 prefers block_norm_eps over rms_norm_eps for block norms
    NORM_EPS = cfg.contains("block_norm_eps")
                 ? cfg["block_norm_eps"].get<float>()
                 : NORM_EPS;

    // conv-specific parameters
    CONV_DIM = cfg.contains("conv_dim")
                 ? cfg["conv_dim"].get<unsigned int>()
                 : DIM;

    CONV_DIM_OUT = cfg.contains("conv_dim_out")
                     ? cfg["conv_dim_out"].get<unsigned int>()
                     : DIM;

    CONV_L_CACHE = cfg.contains("conv_L_cache")
                     ? cfg["conv_L_cache"].get<unsigned int>()
                     : 0;

    CONV_BIAS = cfg.contains("conv_bias")
                  ? cfg["conv_bias"].get<bool>()
                  : false;
    TIE_WORD_EMBEDDINGS = true;
  } catch (const std::exception &e) {
    throw std::runtime_error("Lfm2CausalLM: config parsing error");
  }
}

void Lfm2CausalLM::registerCustomLayers() {
  CausalLM::registerCustomLayers();
  Lfm2Transformer::registerCustomLayers();
}

Lfm2CausalLM Lfm2CausalLM::createTestModel() {
  // Minimal JSON config for testing
  json cfg;
  cfg["vocab_size"] = 65536;
  cfg["hidden_size"] = 1536;
  cfg["num_hidden_layers"] = 2;
  cfg["num_attention_heads"] = 24;
  cfg["num_key_value_heads"] = 8;
  cfg["head_dim"] = 64;
  cfg["intermediate_size"] = 10240;
  cfg["rope_theta"] = 1000000;
  cfg["rms_norm_eps"] = 1e-05;
  cfg["tie_word_embeddings"] = true;
  cfg["max_position_embeddings"] = 128000;

  json gen_cfg;
  gen_cfg["max_new_tokens"] = 1;

  json nntr_cfg;
  nntr_cfg["init_seq_len"] = 8;
  nntr_cfg["batch_size"] = 1;
  nntr_cfg["model_tensor_type"] = "FP32-FP32";
  nntr_cfg["memory_swap"] = false;
  nntr_cfg["tokenizer_file"] = "";

  return Lfm2CausalLM(cfg, gen_cfg, nntr_cfg);
}

} // namespace causallm
